version: "3.9"

services:
  inference:
    build: 
      context: ./inference
      dockerfile: Dockerfile.inference
    expose:
      - 8080

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - 8501:8501
    depends_on:
      - inference
    links:
      - inference
