name: Publish image

on:
  push:
    branch:
      - main

jobs:
  Publish-image:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push streamlit
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: Dockerfile
          push: true
          tags: seyco/frontend-streamlit:latest
      - 
        name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./inference
          file: Dockerfile
          push: true
          tags: seyco/backend-streamlit:latest